language: php

php:
  - 5.6
  - 7
  - 7.0
  - 7.1
  - hhvm

sudo: false

install:
  - composer selfupdate
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then
      composer require 'codeclimate/php-test-reporter:*' 'satooshi/php-coveralls:*';
    else
      composer install;
    fi

before_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then pecl install runkit; fi

script:
  - composer travis

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: f7cda3c831806b53c3a4c7ba6a7585da152bef2bd29ac53bf512cea748d5ea40
